### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [weibeld/Prework_Todo_App#1]
Thank you for your Android submission, Daniel Weibel!

😇 Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by kungfoolabs** [comment]
Hey Daniel!

Thanks for your submission! Great work! It looks like you were able to successfully complete the assignment. Overall, I really liked the additional effort you made to build out additional features and improve the UX

### The Good
- Solid understanding of Android fundamentals!
- Really liked the UX and being able to select priority/due date from the main activity. You were the only one to do this! 
- Great use of SQLlite for persisting data
- Use of Fragments to show date selector!

### Next step

Let's schedule a quick call to confirm that this course is a right fit for you. 
We also would like to know a little more about your experience. 
Please book a slot from [here](https://calendly.com/harley/15m).

**Comment by weibeld** [comment]
Hi,

Thanks for your feedback! In the meantime, I further improved the app. Now the input form is a separate fragment which is used in both the MainActivity and the EditActivity which allows to avoid code repetition. I will add further improvements in the future. I also scheduled a slot for the call.
